({ library(arrow); library(reticulate); use_condaenv("cudf"); cudf <- import("cudf") })
x <- cudf$read_csv(file, sep = "\t")
print(x)
a <- x$head()
b <- x$tail()
c <- x$take(sample(x$shape[[1]], 100) - 1L)
d <- x$take(which(as.vector(x$X1$to_arrow() == "helpless_sheep")))
({ x$add_column("X2_nchar", x$X2$str$len()); e <- x$groupby("X1")$X2_nchar$mean() })
